### PR TITLE
fix: open link in Safari if link has target blank

### LINKED ISSUE #502: [iOS] Links inside the content do not open with a short press
In OpenedX app links inside the content do not open with a short press, only by calling the menu through a long press on the link. 
https://github.com/user-attachments/assets/e2a266a3-d315-4bf0-a185-16d668ffaa0d

At the same time in edX app ("old" app) and in Android OpenedX app links opens as usual, with a short press
https://github.com/user-attachments/assets/6d12cd9b-c521-4d92-ab16-484061efea4f

Links inside the content should open also with a short press, not only with long press on the link.

[Content example](https://learning.edx.org/course/course-v1:MITx+15.480x+3T2021/block-v1:MITx+15.480x+3T2021+type@sequential+block@cec8808828d843ec95f9a3c35554e296/block-v1:MITx+15.480x+3T2021+type@vertical+block@251efc0a9a2c45f5988bc22e7c87dfa1)

### PR DESCRIPTION
**Pull request by rnr**
This PR fixes issue https://github.com/openedx/openedx-app-ios/issues/502
When tag <a> contains `target="_blank"` we open this link in Safari browser

### CODE REVIEW

File: Core/Core/View/Base/Webview/WebView.swift [hunk 1]
```diff
@@ -126,6 +126,19 @@ public struct WebView: UIViewRepresentable {
...
+            for navigationAction: WKNavigationAction,
+            windowFeatures: WKWindowFeatures
+        ) -> WKWebView? {
+            if navigationAction.targetFrame == nil, let url = navigationAction.request.url {
+                if UIApplication.shared.canOpenURL(url) {
+                    UIApplication.shared.open(url)
+                }
+            }
+            return nil
+        }
```
Comment (saeedbashir) [inline Core/Core/View/Base/Webview/WebView.swift]: It's working fine and addressing the underlying issue. But as per the documentation this delegate method is used to `Creates a new web view.` but I guess it's for the app and not for the external like opening a link in safari.

In the production app, it's handled in the delegate method. `decidePolicyFor navigationAction`. Do we need to update it or it's fine?

```
public func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
            let isWebViewDelegateHandled = !(webViewDelegate?.webView(webView, shouldLoad: navigationAction.request) ?? true)
            if isWebViewDelegateHandled {
                decisionHandler(.cancel)
            } else {
                switch navigationAction.navigationType {
                case .linkActivated:
                    if let url = navigationAction.request.url, UIApplication.shared.canOpenURL(url) {
                        UIApplication.shared.open(url, options: [:], completionHandler: nil)
                    }
                    decisionHandler(.cancel)
                default:
                    decisionHandler(.allow)
                }
            }
        }

Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: `target=blank` is forcing to open link in in new window - it's why `createWebViewWith` method is working here. But you're right and we could use `decidePolicyFor navigationAction` too. I'll do a little refactor. Thank you

File: Core/Core/View/Base/Webview/WebView.swift [hunk 2]
```diff
@@ -158,20 +145,23 @@ public struct WebView: UIViewRepresentable {
...
-                        UIApplication.shared.open(url, options: [:])
-                    }
-                } else if navigationAction.navigationType == .formSubmitted {
-                    return .allow
+            switch navigationAction.navigationType {
+            case .other:
+                return .allow
+            case .linkActivated:
+                await MainActor.run {
+                    UIApplication.shared.open(url, options: [:])
```
Comment (saeedbashir) [inline Core/Core/View/Base/Webview/WebView.swift]: It would be nice if you can check whether the link is openable or not before opening the link.

File: Core/Core/View/Base/Webview/WebView.swift [hunk 3]
```diff
@@ -158,20 +145,23 @@ public struct WebView: UIViewRepresentable {
...
                 }
                 return .cancel
+            case .formSubmitted:
+                return .allow
+            default:
+                if !baseURL.isEmpty, !url.absoluteString.starts(with: baseURL) {
+                    return .cancel
+                } else {
+                    return .allow
+                }
```
Comment (saeedbashir) [inline Core/Core/View/Base/Webview/WebView.swift]: we can have only one case, `.linkActivated` and all the other cases can be handled in `default:`

File: Core/Core/View/Base/Webview/WebView.swift (hunk 2 above)
Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: done

File: Core/Core/View/Base/Webview/WebView.swift (hunk 3 above)
Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: by some reason types `.other` and `.formSubmitted` was allowed and all other was cancelled `if !baseURL.isEmpty, !url.absoluteString.starts(with: baseURL)`
do you have some idea why?
I left the same logic as before

File: Core/Core/View/Base/Webview/WebView.swift [hunk 4]
```diff
@@ -145,20 +145,23 @@ public struct WebView: UIViewRepresentable {
             }
             
             let baseURL = await parent.viewModel.baseURL
-            if !baseURL.isEmpty, !url.absoluteString.starts(with: baseURL) {
-                if navigationAction.navigationType == .other {
-                    return .allow
-                } else if navigationAction.navigationType == .linkActivated {
-                    await MainActor.run {
+            switch navigationAction.navigationType {
+            case .other, .formSubmitted:
```
Comment (saeedbashir) [inline Core/Core/View/Base/Webview/WebView.swift]: In this case, do we need to handle `formResubmitted` as well? or it's fine to through it to default?

Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: by `default` for not baseURL `.cancel` is returning for any type.

Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: `.allow` was added for type `.other` and `.formSubmitted` - I don't know the reason. But do you think it's good idea to change this now?

Comment (saeedbashir) [reply Core/Core/View/Base/Webview/WebView.swift]: let's keep this for a while, but I would say if we are adding `.formSubmitted` we should also add `.formResubmitted`, thoughts?

Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: Perhaps we should. But we need to have some request from QA for this when something doesn't work. I mean current state (with only `.other` and `.formSubmitted` for baseURL) was tested and no issues was found. Like `if it ain't broke, don't fix it` you know.

**Review by saeedbashir — APPROVED** [review]
LGTM 👍

File: Core/Core/View/Base/Webview/WebView.swift (hunk 4 above)
Comment (rnr) [reply Core/Core/View/Base/Webview/WebView.swift]: added `. formResubmitted` as @saeedbashir  suggested

**Review by forgotvas — APPROVED** [review]
